version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - /mnt/efs/fs1/mysql:/var/lib/mysql:rw,delegated
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     volumes:
       - /mnt/efs/fs1/wp-uploads:/var/www/html/wp-content/uploads:rw,delegated
     build: .
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
<<<<<<< HEAD
     db_data: {}       
=======
     db_data: {}
>>>>>>> a09a2d4f1ff7df6a8efc3f3e8bdc67d94668b3cd
     wordpress: {}
